all:
  hosts:
    servicenow-jumpbox:
      ip: 127.0.0.1
      ansible_connection: local
    servicenow-1:
      ip: 172.16.42.43
      access_ip: 172.16.42.43
      ansible_host: 172.16.42.43
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/serviceNow.pem
