---
- hosts: sn-1
  tasks:
  - name: Installing packages - pip, pip3, docker and docker-compose
    become: yes
    apt:
       name: "{{ packages }}"
       state: present
       update_cache: true
    vars:
      packages:
      - python-pip
      - python3-pip
      - docker.io

  - name: Showing output for apt install
    shell: sudo apt list --installed | grep -i -e python-pip -e python3-pip -e docker.io -e docker-compose
    register: apt_install

  - debug: var=apt_install.stdout_lines

  - name: Install PIP docker client
    executable: pip-3.3
    pip:
       name: 
         - docker
         - docker-py==1.10.6
         - docker-compose==1.9.0

  - name: Restart and check PIP
    shell: pip freeze
    register: pip_output

  - debug: var=pip_output.stdout

  - name: Clone GIT Repo for docker-compose and dockerfile builds
    git:
       repo: https://github.com/vaultsystems/docker-servicenow.git
       dest: /home/ubuntu/servicenow

  - name: Copy the servicenow zip file from the jumpbox to ServiceNow host
    copy:
        src: /home/ubuntu/glide-helsinki-03-16-2016__patch0-hotfix1-05-16-2016_05-16-2016_1044.zip
        dest: /home/ubuntu/servicenow/glide-helsinki-03-16-2016__patch0-hotfix1-05-16-2016_05-16-2016_1044.zip
