---
- hosts: sn-1
  tasks:
  - name: Installing packages - pip, pip3, docker and docker-compose
    become: yes
    apt:
       name: "{{ packages }}"
       state: present
       update_cache: true
    vars:
      packages:
      - python3-pip
      - python-pip
      - docker.io

  - name: Install PIP docker client
    pip:
       state: present
       name: 
         - docker
         - requests
         - docker-compose==1.9.0
       executable: /usr/bin/pip
       
  - name: Install PIP3 docker client
    pip:
       state: present
       name: 
         - docker
         - requests
         - docker-compose==1.9.0
       executable: /usr/bin/pip3

  - name: Clone GIT Repo for docker-compose and dockerfile builds
    git:
       repo: https://github.com/vaultsystems/docker-servicenow.git
       dest: /home/ubuntu/servicenow

  - name: Copy the servicenow zip file from the jumpbox to ServiceNow host
    copy:
        src: /home/ubuntu/glide-helsinki-03-16-2016__patch0-hotfix1-05-16-2016_05-16-2016_1044.zip
        dest: /home/ubuntu/servicenow/glide-helsinki-03-16-2016__patch0-hotfix1-05-16-2016_05-16-2016_1044.zip
