- hosts: servicenow-1
  tasks:
    - debug:
        msg: play1

- name: Include a play after another play
  import_playbook: ~/serviceNow-ansible/init.yml
  
- name: Build docker environment
  import_playbook: ~/serviceNow-ansible/docker-init.yml
