---
- hosts: sn-1
  tasks:
  - name: Installing packages - pip, pip3, docker and docker-compose
    become: yes
    apt:
       name: "{{ packages }}"
       state: present
       update_cache: true
    vars:
      packages:
      - python-pip
      - python3-pip
      - docker.io
      - docker-compose

  - name: Showing output for apt install
    shell: sudo apt list --installed | grep -i -e python-pip -e python3-pip -e docker.io -e docker-compose
    register: apt_install

  - debug: var=apt_install.stdout_lines

  - name: Install PIP docker client
    pip:
       name: 
         - docker
         - docker-py
       extra_args: --user
       executable: pip-9.0.1

  - name: Restart and check PIP
    shell: pip freeze
    register: pip_output

  - debug: var=pip_output.stdout

  - name: Clone GIT Repo for docker-compose and dockerfile builds
    git:
       repo: https://github.com/vaultsystems/docker-servicenow.git
       dest: /home/ubuntu/servicenow

  - name: Copy the servicenow zip file from the jumpbox to ServiceNow host
    copy:
        src: /home/ubuntu/glide-helsinki-03-16-2016__patch0-hotfix1-05-16-2016_05-16-2016_1044.zip
        dest: /home/ubuntu/servicenow/glide-helsinki-03-16-2016__patch0-hotfix1-05-16-2016_05-16-2016_1044.zip

  - name: Build the serviceNow docker image from dockerfile
    become: true
    become_method: sudo
    docker_image:
       name: servicenow
       build:
         path: /home/ubuntu/servicenow
       source: build

  - name: Check if container is running
    become: true
    become_method: sudo
    shell: sudo docker image list
    register: output

  - debug: var=output.stdout_lines

  - name: Create and start services
    become: true
    become_method: sudo
    docker_compose:
       project_src: /home/ubuntu/servicenow
    register: dc_output

  - debug:
      var: dc_output
