---
- hosts: sn-1
  tasks:
  - name: Docker
    become: yes
    apt: 
       name: "{{ packages }}" 
       state: present 
       update_cache: true
    vars:
      packages:
      - python-pip
      - python3-pip
      - docker-compose

  - pip:
       name: "{{ packages }}"
    vars:
      packages:
      - docker==2.0.0
      - docker-py==1.10.6

  - name: Clone GIT Repo
    git:
       repo: https://github.com/vaultsystems/docker-servicenow.git
       dest: /home/ubuntu/servicenow

  - name: copy zip file
    copy:
        src: /home/ubuntu/glide-helsinki-03-16-2016__patch0-hotfix1-05-16-2016_05-16-2016_1044.zip
        dest: /home/ubuntu/servicenow/glide-helsinki-03-16-2016__patch0-hotfix1-05-16-2016_05-16-2016_1044.zip


  - name: Dockerfile build
    become: true
    docker_image:
        build:
           path: /home/ubuntu/servicenow
        name: servicenowTest:latest
        source: build
