---
- hosts: sn-1
  tasks:
  - name: Docker
    become: yes
    become_method: sudo
    apt:
       name: python-pip
       state: present
       update_cache: true
       
  - name: Docker-Compose
    become: yes
    become_method: sudo
    apt:
       name: docker-compose
       state: present
       update_cache: true

  - pip:
       name: docker

  - name: Clone GIT Repo
    git:
       repo: https://github.com/vaultsystems/docker-servicenow.git
       dest: /home/ubuntu/servicenow

  - name: copy zip file
    copy:
        src: /home/ubuntu/glide-helsinki-03-16-2016__patch0-hotfix1-05-16-2016_05-16-2016_1044.zip
        dest: /home/ubuntu/servicenow/glide-helsinki-03-16-2016__patch0-hotfix1-05-16-2016_05-16-2016_1044.zip
