---
- hosts: sn-1
  tasks:
  - name: Install packages
    apt:
       state: present
    with_items:
       - docker

  - name: Clone GIT Repo
    git:
       repo: https://github.com/vaultsystems/docker-servicenow.git
       dest: /home/ubuntu/servicenow
